### ISSUE TITLE
App goes to blank screen after unbonding DHX

### ISSUE THREAD

**Issue by andresovela** [mxc-foundation/supernode-app#263]
When you unbond DHX, the app goes into a blank black screen that you cannot leave. You have to kill the app to start over.

https://user-images.githubusercontent.com/8990961/124559133-a786d400-de3b-11eb-8799-a9aa0564ccec.MOV

**Comment by zhbh** [comment]
Hi, @andresovela. This issue has been solved with the latest version. Anyway, thank you for reporting this issue.
