### ISSUE TITLE
Keyboard in unbond DHX screen does not go away once you bring it up

### ISSUE THREAD

**Issue by andresovela** [mxc-foundation/supernode-app#266]
Once you bring up the keyboard, it hides the `Proceed` button behind it and you can't tap it because the keyboard can't be brought down. So far my workaround is to slightly pull back the screen from the left and then the keyboard goes away, but IMO the keyboard should have an `OK` button or something to accept the input instead.

**Comment by zhbh** [comment]
Our resolution is that When you tap on the page anywhere with a keyboard, the keyboard will bring it down.

**Comment by andresovela** [comment]
Cool, that works for me.

**Comment by andresovela** [comment]
I still have this issue in 1.12.2 (199) on iOS
