### ISSUE TITLE
[iOS] After first connecting miner, only data tab shows a UI.

### ISSUE THREAD

**Issue by thedokuijf** [mxc-foundation/supernode-app#269]
When I first connected miner, went onto the miner page where you should be able to see Health - Revenue - Data via the tabs.

Only the data tab worked at first, until the miner had received some frames &or synced back to the app. Then Health & Revenue showed UI information again.

If this is by design, suggestion to add a designed state for that instead of nothing (I could only see the tabs, and background of a layout which should have shown something)

(Should be tried to reproduce first, not sure about Android)

**Comment by zhbh** [comment]
#276

**Comment by jeffstahlnecker** [comment]
Duplicate issue.
