### ISSUE TITLE
DHX mining calendar is missing data

### ISSUE THREAD

**Issue by cslowik** [mxc-foundation/supernode-app#273]
The new DHX mining calendar is missing data.

With the addition of scroll I'd expect that previous earnings would be visible.
Current week earnings are not visible either.

I also can't see cool down period or my unbond requests

Flying blind with dhx 😎

![IMG_1966](https://user-images.githubusercontent.com/2077997/125104561-5fadba00-e092-11eb-9ae1-efdcbab5bf1c.PNG)

**Comment by cslowik** [comment]
Just to add more info - I deleted and reinstalled the beta app, and now there are not any numbers at all on my calendar. no blue line showing cool down period.

**Comment by jeffstahlnecker** [comment]
> Just to add more info - I deleted and reinstalled the beta app, and now there are not any numbers at all on my calendar. no blue line showing cool down period.

Odd -- after reinstalling the app I'm still getting the data for the past seven days. That said, only the data for the past seven days.

@zhbh will dig into it to ensure the calendar has full historical data, and confirm that it's pulling data from the API, and not just the local cache.

**Comment by andresovela** [comment]
I see the same issue in today's released version [1.12.2 (199)] on iOS 

![image](https://user-images.githubusercontent.com/8990961/125983499-25e28b5f-42e1-4f1c-a33c-feabfcfce47d.png)

**Comment by Burnedby89** [comment]
My results show the last 6 days. Should the "+1.2 DHX / month" be updated to "week" or will it aggregate the full month once the historical issue is resolved? 

In addition, the totals of the dates displayed is 1.255, so I think it should round up to 1.3?

![Screenshot_20210718-114549.png](https://user-images.githubusercontent.com/87612891/126075430-03d7ae47-13c3-4f40-a43c-e12310bc1b07.png)

**Comment by Burnedby89** [comment]
My calendar hasn't updated since the 17th.

![Screenshot_20210719-214734.png](https://user-images.githubusercontent.com/87612891/126254314-030c5262-11f0-4897-a338-9d99d7abc5d3.png)

**Comment by andresovela** [comment]
Any updates on this issue?
