### ISSUE TITLE
Refresh miner health homepage

### ISSUE THREAD

**Issue by masterchiev** [mxc-foundation/supernode-app#277]
When I try to refresh the homepage in the app. The new miner health area will not be updated.

**Comment by zhbh** [comment]
It needs to take a while for the backend ready to update.
Anyway, I will check it out.

**Comment by zhbh** [comment]
Hi, @masterchiev. I test it again and again, which is fine. Can you give more detail for us? Such as Now does it work? Does it connect with the internet very well? which is your supernode? Has your miner been added to the miner page?

**Comment by rd101rahul** [comment]
Retested and it looks good.
Closing the issue as there hasn't been response for more details needed since long. Please feel free to Reopen the issue if it still exists, Thanks!
