### ISSUE TITLE
[Bug]: Month revenue and data results in grey screen

### ISSUE THREAD

**Issue by masterchiev** [mxc-foundation/supernode-app#280]
### What happened?

See video. Shows grey screen on the monthly revenue and monthly data overall in the miner section.

### Version

1.13.0 (Beta)

### Which OS are you seeing the problem on?

iOS

**Comment by masterchiev** [comment]
Can’t add a video. But when you are in the miner. Click on revenue and go to monthly. Swipe to the left. You see grey screen.

**Comment by jeffstahlnecker** [comment]
Resolved in 1.13.1.
