### ISSUE TITLE
[Bug]: add address book entry, text boxes obscured for last two text boxes name and memo.

### ISSUE THREAD

**Issue by havadevs** [mxc-foundation/supernode-app#285]
### Contact Details [Discord Username]

jibo

### What happened?

android moto g4 and ios iphone SE 2017

The first address text box is visible and usable however, for name and memo texts, the text widget obscures both  and I'm unable to view what I'm typing after positioning the cursor in the box.

### Version

1.13.0 (Beta)

### Which OS are you seeing the problem on?

iOS, Android

**Comment by havadevs** [comment]
![Screenshot_20210721-103342.png](https://user-images.githubusercontent.com/66387291/126458301-ecee1998-1b4a-4c01-a5c0-553dc9342cc1.png)

**Comment by havadevs** [comment]
Moto G4 Android 7

**Comment by rd101rahul** [comment]
This issue is addressed and the fix will be available in next build, Thanks!
