### ISSUE TITLE
[Bug]: Dark mode for android? Light mode only seen.

### ISSUE THREAD

**Issue by havadevs** [mxc-foundation/supernode-app#286]
### Contact Details [Discord Username]

jibo

### What happened?

When testing ios, the dark mode was automatically on after I opened the app.
However, with android I've only seen the light mode. The version is correct 1.13.0 (300)
I cannot find any icon or app settings for dark mode, perhaps I need a tip to find the setting.

Moto g4. android 7.0

### Version

1.13.0 (Beta)

### Which OS are you seeing the problem on?

Android

**Comment by jeffstahlnecker** [comment]
Hi @havadevs --- dark mode settings are reliant on the OS settings (Settings -> Display -> Theme). So if the Android phone is set for dark mode as default, then the dark mode will show up in the app. We plan to add a toggle soon that allows you to manually activate dark mode in the future.

**Comment by havadevs** [comment]
cheers!
