### ISSUE TITLE
[Bug]: Dark mode touch feedback "see more" stats display white labels without data

### ISSUE THREAD

**Issue by havadevs** [mxc-foundation/supernode-app#290]
### Contact Details [Discord Username]

jibo

### What happened?

Dark mode - the touch feedback on the "see more" daily details columns display empty data, only a white label is visible without any data.  This is the case for all daily details - revenue, data, up time.

### Version

1.13.0 (Beta)

### Which OS are you seeing the problem on?

Android

**Comment by jeffstahlnecker** [comment]
@havadevs always helpful if you an add a screenshot. You can drag those directly into the text box.

**Comment by havadevs** [comment]
![Screenshot_20210721-092129](https://user-images.githubusercontent.com/66387291/126448414-5bf56da8-3785-43ee-9f45-8d416933a6a3.jpg)
![Screenshot_20210721-092151](https://user-images.githubusercontent.com/66387291/126448419-8ac8626c-74c3-47de-8888-27fd34dbfb3a.jpg)
![Screenshot_20210721-092159](https://user-images.githubusercontent.com/66387291/126448423-5e38f32c-c1c2-453e-9d35-dad4797d3e1c.jpg)
![Screenshot_20210721-092227](https://user-images.githubusercontent.com/66387291/126448424-583531ef-fbab-4459-9489-66ee00474653.jpg)

**Comment by havadevs** [comment]
Night mode on Samsung S8, Android 9
