### ISSUE TITLE
Uptime of 16 hours only on one m2 pro.

### ISSUE THREAD

**Issue by havadevs** [mxc-foundation/supernode-app#292]
After 16:00 2021-07-20, the system logs continue to be normal however, the app indicated a downtime from about 16:00 to 24:00.

Supernode: lora

My other 4 pros reported a full 24 hours uptime. 

Is it possible to provide diagnostic downtime error messages in the app or in the system logs? ![Screenshot_20210721-092837.jpg](https://user-images.githubusercontent.com/66387291/126451438-f8c45eb3-4dcd-4766-8959-421a7a61ab1e.jpg)

**Comment by jeffstahlnecker** [comment]
This is a specific issue, potentially with one M2 Pro and doesn't represent a bug in the mobile application. Please reach out to support@matchx.io to clarify the issue with that M2 Pro. You can also use this guide to troubleshoot: https://dev.mxc.org/docs/tutorials/m2-pro/troubleshooting
