### ISSUE TITLE
[Bug]: Can't scroll up in the DHX calendar view

### ISSUE THREAD

**Issue by andresovela** [mxc-foundation/supernode-app#311]
### Contact Details [Discord Username]

andresovela

### What happened?

Once you scroll down past the `Today - Cool-off - Unbonded/days left to cool-off` header, it's not possible to scroll back up to see your mining stats.

### Version

1.13.2 (Beta)

### Which OS are you seeing the problem on?

iOS

### Anything else?

Video

https://user-images.githubusercontent.com/8990961/127841912-35902602-a5e0-421c-9024-6244417f596d.MOV

**Comment by rd101rahul** [comment]
This issue has been addressed and the fix would be available with next build.

**Comment by rd101rahul** [comment]
Closing the issue as the fix is available in 1.13.4
Please reopen the issue it the bug still exists, Thanks!

**Comment by andresovela** [comment]
Looks fixed to me :)
