### ISSUE TITLE
Remove "Day" in Revenue Graphs

### ISSUE THREAD

**Issue by Burnedby89** [mxc-foundation/supernode-app#325]
Very minor, but I think "Day" should removed from each graph in the Revenue section (highlighted in red)
![Screenshot_20210824-162403~4.png](https://user-images.githubusercontent.com/87612891/130713171-8b09391c-c798-4664-8a19-1f78f346dd42.png)![Screenshot_20210824-162359.png](https://user-images.githubusercontent.com/87612891/130713188-efb9a748-8fdc-4925-ad0c-99923a990622.png)![Screenshot_20210824-162356.png](https://user-images.githubusercontent.com/87612891/130713201-041f4ceb-d3e0-4a2b-b692-4e13d12573a0.png)

**Comment by rd101rahul** [comment]
Thanks for highlighting this.
We have noticed and fixed this. Fix would be available with latest version, Thanks!
